"""empty message

Revision ID: 937fecd82ec9
Revises: 
Create Date: 2022-04-16 13:34:28.819884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937fecd82ec9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sitemap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('is_scraped', sa.Boolean(), nullable=True),
    sa.Column('scraped_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sitemap')
    # ### end Alembic commands ###
